# Generated by Django 4.0.4 on 2023-11-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
