# Generated by Django 4.0.4 on 2023-11-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryApp', '0002_order_payment_mode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(to='bakeryApp.cartitem'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
